repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: generate-docs
        name: Generate Sphinx Documentation
        entry: bash generate_all_docs.sh
        language: system
        always_run: true
        pass_filenames: false
