name: Trainer CI

on:
  push:
    paths:
      - 'trainer/**'
  pull_request:
    paths:
      - 'trainer/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd trainer
        pip install poetry
        poetry install
    - name: Run tests
      run: |
        cd trainer
        poetry run tox
